jwt.secret=change_me_to_a_long_random_secret_key
jwt.expiration.seconds=3600
scheduler.interval=100
scheduler.timeUnit=MILLISECONDS

# EMAIL
email.username=your_email@example.com
email.password=your_email_password
email.from=your_email@example.com
mail.smtp.host=127.0.0.1
mail.smtp.port=25
mail.smtp.auth=false
mail.smtp.starttls.enable=true

# SMPP
smpp.host=localhost
smpp.port=2775
smpp.system_id=smppclient1
smpp.password=password
smpp.system_type=OTP
smpp.source_addr=OTPService