jwt.expiration.seconds=3600
scheduler.interval=1
scheduler.timeUnit=SECONDS

# EMAIL
email.username=your_email@example.com
email.from=your_email@example.com
mail.smtp.host=smtp
mail.smtp.port=1025
mail.smtp.auth=false
mail.smtp.starttls.enable=true

# SMPP
smpp.host=smpp
smpp.port=2775
smpp.system_id=smppclient1
smpp.system_type=OTP
smpp.source_addr=OTPService

# TELEGRAM
telegram.api.base-url=https://api.telegram.org

# FILE
otp.file.path=${OTP_FILE_PATH}